# Generated by Django 4.0.4 on 2022-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_amount_raised_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amount_required',
        ),
        migrations.RemoveField(
            model_name='project',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
