# Generated by Django 3.2 on 2022-05-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_amount_raised_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sub_body2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_title2',
        ),
    ]
