# Generated by Django 3.2 on 2022-05-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', '---------'), ('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('title', models.CharField(choices=[('', '---------'), ('Computer Training (Desktop Publishing)', 'Computer Training (Desktop Publishing)'), ('Musical Instruments (Piano/ Guitar)', 'Musical Instruments (Piano/ Guitar)'), ('Photography And Video Editing', 'Photography And Video Editing'), ('Communication Management', 'Communication Management'), ('Web Designing And Hosting', 'Web Designing And Hosting'), ('Insurance Administration', 'Insurance Administration'), ('Catering And Small Chops', 'Catering And Small Chops'), ('Project Management', 'Project Management'), ('Fashion Designing', 'Fashion Designing'), ('Gele Tying', 'Gele Tying'), ('Hair Making', 'Hair Making'), ('Communication Management', 'Communication Management'), ('Make Over', 'Make Over'), ('Craft', 'Craft'), ('Sound Engineering', 'Sound Engineering'), ('Acting/Dancing', 'Acting/Dancing'), ('CV Clinic', 'CV Clinic')], max_length=1000)),
                ('fees', models.TextField(blank=True, null=True)),
                ('image_670_by_478', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
