# Generated by Django 4.0.4 on 2022-05-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_body2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_body3',
            field=models.TextField(),
        ),
    ]
