# Generated by Django 4.0.4 on 2022-05-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_options_remove_about_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='image_290_by_330',
        ),
        migrations.AddField(
            model_name='about',
            name='image_510_by_580',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
