# Generated by Django 4.0.4 on 2022-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_image_about_image_290_by_330_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='author',
        ),
    ]
