# Generated by Django 4.0.4 on 2022-05-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_about_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='sub_body2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='sub_body3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='sub_title2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='sub_title3',
        ),
    ]
