# Generated by Django 3.2 on 2022-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('training', models.CharField(choices=[('', '---------'), ('Computer Training (Desktop Publishing)', 'Computer Training (Desktop Publishing)'), ('Musical Instruments (Piano/ Guitar)', 'Musical Instruments (Piano/ Guitar)'), ('Photography And Video Editing', 'Photography And Video Editing'), ('Communication Management', 'Communication Management'), ('Web Designing And Hosting', 'Web Designing And Hosting'), ('Insurance Administration', 'Insurance Administration'), ('Catering And Small Chops', 'Catering And Small Chops'), ('Project Management', 'Project Management'), ('Fashion Designing', 'Fashion Designing'), ('Gele Tying', 'Gele Tying'), ('Hair Making', 'Hair Making'), ('Communication Management', 'Communication Management'), ('Make Over', 'Make Over'), ('Craft', 'Craft'), ('Sound Engineering', 'Sound Engineering'), ('Acting/Dancing', 'Acting/Dancing'), ('CV Clinic', 'CV Clinic')], max_length=1000)),
                ('your_parish', models.CharField(choices=[('', '---------'), ('St. John the Evangelist Agah', 'St. John the Evangelist Agah'), ('St. Jude Thadius Erunwe', 'St. Jude Thadius Erunwe'), ('St. Anthony Mary Claret Eyita', 'St. Anthony Mary Claret Eyita'), ('St. Augustine Ikorodu', 'St. Augustine Ikorodu')], max_length=1000)),
                ('support_line', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('', '---------'), ('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enroll',
                'verbose_name_plural': 'Enroll',
                'ordering': ['-id'],
            },
        ),
    ]
