# Generated by Django 3.2 on 2022-05-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20220512_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
