# Generated by Django 3.2 on 2022-05-15 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'verbose_name': 'Enroll', 'verbose_name_plural': 'Enroll'},
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='id',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='view_count',
        ),
        migrations.AddField(
            model_name='enroll',
            name='form_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enroll',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='your_parish',
            field=models.CharField(choices=[('', '---------'), ('St. John the Evangelist Agah', 'St. John the Evangelist Agah'), ('St. Jude Thadius Erunwe', 'St. Jude Thadius Erunwe'), ('St. Anthony Mary Claret Eyita', 'St. Anthony Mary Claret Eyita'), ('St. Augustine Ikorodu', 'St. Augustine Ikorodu'), ('Other', 'Other')], max_length=1000),
        ),
    ]
