# Generated by Django 3.2 on 2022-05-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20220515_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='enter_your_parish',
            field=models.TextField(blank=True, null=True),
        ),
    ]
