# Generated by Django 3.2 on 2022-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_enroll_enter_your_parish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='form_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
