# Generated by Django 4.0.4 on 2022-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_training_options_training_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='training',
            name='amount_required',
        ),
        migrations.RemoveField(
            model_name='training',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='training',
            name='facilitator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
