# Generated by Django 3.2 on 2022-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_training_amount_raised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
