# Generated by Django 3.2 on 2022-05-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='sub_body2',
        ),
        migrations.RemoveField(
            model_name='training',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='training',
            name='sub_title2',
        ),
    ]
