# Generated by Django 3.2 on 2022-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_training_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
