# Generated by Django 4.0.4 on 2022-05-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='image_50_by_50',
            new_name='image_370_by_410',
        ),
    ]
