# Generated by Django 4.0.4 on 2022-05-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_image_50_by_50_team_image_370_by_410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='testimony',
        ),
    ]
