# Generated by Django 4.0.4 on 2022-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_team_rating_remove_team_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_570_by_640',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='image_770_by_445',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='speech',
            field=models.TextField(blank=True, null=True),
        ),
    ]
