# Generated by Django 3.2 on 2022-05-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_image_570_by_640_team_image_770_by_445_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Committee', 'verbose_name_plural': 'Committee'},
        ),
    ]
