# Generated by Django 4.0.4 on 2022-05-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Testimonial',
        ),
    ]
