# Generated by Django 4.0.4 on 2022-05-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='slug',
        ),
    ]
