# Generated by Django 3.2 on 2022-05-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Board', 'verbose_name_plural': 'Board'},
        ),
    ]
